raw_file_path:
  patient: ./Patient
  clinical: ./Clinical
  practice: ./Practice
  diagnosis_hes: ./hes_diagnosis_hosp_16_049R.txt
  hes_death: ./death_patient_16_049R.txt
  eligible: ./linkage_eligibility.txt
  med2read: ./medical.txt
  icdNHS:  ./final_mapping.csv
  hes_procedure: ./hes_procedures_epi_16_049R.txt
  prod2bnf: ./product.txt
  therapy: ./Therapy
  test: ./Test
  additional: ./Additional

mid_stage_file_path:
  mid_stage_dir: ./data
  mapped_diagnosis: diagnoses.parquet
  medication: medication.parquet
  hes_procedure: hes_procedure.parquet
  cprd_test: cprd_test.parquet
  additional: additional.parquet
  hf_data: HF_1985_2015_raw.parquet
  bmi: bmi.parquet
  bp_low: bp_low.parquet
  bp_high: bp_high.parquet
  smoke: smoke.parquet
  alcohol: alcohol.parquet
  downstream: pat_downstrean.parquet


task: generate_pat_list.main